In [ ]:
# seaborn 패키지를 불러와서 가지고 오기!
import pandas as pd
import seaborn as sns

tt =sns.load_dataset('titanic')  # seaborn에서 제공하는 titanic dataset을 tt에 저장

In [ ]:
## 판다스는 데이터프레임과 시리즈 형태로
type(tt)

pandas.core.frame.DataFrame

In [ ]:
tt

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
# dataframe

tt.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# series

tt['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [ ]:
print(tt.dtypes)

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [ ]:
type(tt['pclass'])

pandas.core.series.Series

In [ ]:
tt['pclass']

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: pclass, Length: 891, dtype: int64

In [ ]:
sum(tt['age'])  # 중간에 Nan 포함

nan

In [ ]:
min(tt['age'])

0.42

In [ ]:
max(tt['age'])

80.0

In [ ]:
import numpy as np
np.mean(tt['age'])  # 자동으로 Nan을 제외하고 평균 계산

np.float64(29.69911764705882)

## 데이터 분석에 필요한 기초 문법들
- head(), tail() 데이터 요약 상위, 하위 부분만 출력
    - head(10) 앞 10개
    - tail(10) 뒤 10개
- shape 행,열 확인
- info() 데이터 요약
- describe() 데이터 요약통계
- dytpes 데이터 타입
- columns 컬럼들만

In [ ]:
tt.head(10) # 앞 10개의 행

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [ ]:
tt.tail(10) # 뒤 10개의 행

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
tt.shape # (#행, #열)

(891, 15)

In [ ]:
tt.info() # data 요약

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
tt.describe() # data 요약통계

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
tt.describe(include = 'all') # 숫자형, 범주형 데이터를 모두 포함한 요약통계

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
tt.info() # data 요약

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
print(tt.dtypes)

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [ ]:
## 데이터 타입에 따라 출력도 가능하다.
tt.describe(include=['object','bool','category'])

# object : sex,embarked,who,embark_town,alive / bool : adult_male,alone / category : class,deck

         sex embarked  class  who adult_male deck  embark_town alive alone
count    891      889    891  891        891  203          889   891   891
unique     2        3      3    3          2    7            3     2     2
top     male        S  Third  man       True    C  Southampton    no  True
freq     577      644    491  537        537   59          644   549   537

In [ ]:
tt.describe(include=['number']) # int,float

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
tt.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
for i in list(tt.columns):
  print(i)

survived
pclass
sex
age
sibsp
parch
fare
embarked
class
who
adult_male
deck
embark_town
alive
alone

## 상황에 따른 판다스 기초 문법들
- 데이터의 변수명을 바꾸기
- 예시 데이터를 만들어서 살펴보자!

In [ ]:
## 데이터프레임을 만드는 법
## 데이터프레임은 행과 열의 구조로 이뤄진 형태라서 데이터프레임을 직접 만들 때 행,열 구조로 데이터를 넣어야 한다.

df=pd.DataFrame({'분반':['파문기','SQL','데이터분석','딥러닝'],
             '인워ㄴ':[100,200,300,400]})

In [ ]:
df.columns

Index(['분반', '인워ㄴ'], dtype='object')

In [ ]:
df

      분반  인워ㄴ
0    파문기  100
1    SQL  200
2  데이터분석  300
3    딥러닝  400

In [ ]:
df_new = df.rename(columns={'인워ㄴ':'인원'})
df_new

      분반   인원
0    파문기  100
1    SQL  200
2  데이터분석  300
3    딥러닝  400

In [ ]:
df

      분반  인워ㄴ
0    파문기  100
1    SQL  200
2  데이터분석  300
3    딥러닝  400

In [ ]:
## 컬럼 명을 바꿀 때는 rename
## 데이터프레임.rename(columns={'기존컬럼':'변경할 컬럼'})
df.rename(columns={'인워ㄴ':'인원'})

## 원본데이터에 저장을 한다? 라고 하면
## df_new = df.rename(columns={'인워ㄴ':'인원'})
## df.rename(columns={'인워ㄴ':'인원'}, inplace=True) # 변수와 하지 않고 바로 그 상태로 바꿀 수 있는 함수 inplace=True

      분반   인원
0    파문기  100
1    SQL  200
2  데이터분석  300
3    딥러닝  400

In [ ]:
df.rename(columns={'인워ㄴ':'인원'}, inplace=True) # inplace=True 설정하면 원본 df 자체가 변경

In [ ]:
df

      분반   인원
0    파문기  100
1    SQL  200
2  데이터분석  300
3    딥러닝  400

In [ ]:
df_1 =df.copy() # 원본 데이터는 냅두고 복사한 데이터에서 코드를 실행하는 것이 좋음

In [ ]:
df_1

      분반   인원
0    파문기  100
1    SQL  200
2  데이터분석  300
3    딥러닝  400

### 파생변수 만들기
- 현재의 데이터들을 이용해서 분석도 가능하지만 -> 변수들을 조합하여서 새로운 변수를 만들어 분석할 수 있다.
- 영어, 수학, 과학 점수가 있으면 -> 이 세 개의 변수를 평균으로 바꿔서 하나의 파생변수로도 나타낼 수 있다.
- BDA 상점, 벌점 상점 - 벌점 = 수료가능한 점수
    - 판다스는 직관적으로 만들 수 있다.
    - 판다스의 함수를 이용해서도 만들 수 있다.

In [ ]:
df=pd.DataFrame({'이름':['홍길동','박길동','오길동','이길동'],
             '상점':[10,20,30,40],
            '벌점':[30,5,15,20]})

In [ ]:
df

    이름  상점  벌점
0  홍길동  10  30
1  박길동  20   5
2  오길동  30  15
3  이길동  40  20

In [ ]:
df_1= df.copy()

In [ ]:
df_1

    이름  상점  벌점
0  홍길동  10  30
1  박길동  20   5
2  오길동  30  15
3  이길동  40  20

In [ ]:
df_1['수료가능점수']= df_1['상점'] - df_1['벌점']
## 상점 - 벌점으로 만들면 되는 거 아닌가?

In [ ]:
df_2 = df.copy()

In [ ]:
df_2['수료가능점수'] = df_2['상점'-'벌점']

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
type(df_1['수료가능점수'])

pandas.core.series.Series

In [ ]:
##수료, 수료불가
##수료가능점수 기준에 따라 수료, 수료불가
for i in df_1['수료가능점수']:
    if i > 0:
        print('수료')
    else:
        print('수료불가')

수료불가
수료
수료
수료

In [ ]:
## numpy를 가지고 인덱스를 쉽게 찾아서 필요한 전처리를 진행할 수 있다.
## np.where
## 참이 앞의 값으로 매핑, 거짓이 뒤 값으로 매핑

df_1['수료여부']=np.where(df_1['수료가능점수']>0,'수료','수료불가')

In [ ]:
df_1

    이름  상점  벌점  수료가능점수  수료여부
0  홍길동  10  30     -20  수료불가
1  박길동  20   5      15    수료
2  오길동  30  15      15    수료
3  이길동  40  20      20    수료

In [ ]:
df_1['수료가능점수']>0 # 불리언 타입 출력

0    False
1     True
2     True
3     True
Name: 수료가능점수, dtype: bool

In [ ]:
## 범주형 데이터를 카운팅 하는 간단한 방법
## value_counts()
df_1['수료여부'].value_counts()

수료여부
수료      3
수료불가    1
Name: count, dtype: int64

## loc[ ], iloc[ ]
- 인덱싱 작업

- loc : Location(인덱스) - 처음 생성된 데이터프레임의 인덱스
- iloc : Integer Location (넘버링된 인덱스) - 현재 기준의 데이터프레임의 순서 인덱스 ( 데이터프레임을 조정하거나 재조립하게 되면 그 기준 순서로 넘버링)
    - 데이터프레임.loc[인덱스]
    - 데이터프레임.iloc[인덱스]   
- loc, iloc 은 행과 열 모두 접근 가능하다.
- loc : 컬럼명을 명시적으로 적어줘야 한다.
- iloc : 뒤에도 컬럼을 모두 다 숫자로 int로 적어줘야 한다. 안 그러면 에러가 난다.

In [ ]:
## 슬라이싱 range() 사용
## loc[행,열]
## loc[행:행,열:열]
tt.loc[10:30:2,['survived','pclass']]

    survived  pclass
10         1       3
12         0       3
14         0       3
16         0       3
18         0       3
20         0       2
22         1       3
24         0       3
26         0       3
28         1       3
30         0       1

In [ ]:
tt.loc[10:30,['survived','pclass']]

    survived  pclass
10         1       3
11         1       1
12         0       3
13         0       3
14         0       3
15         1       2
16         0       3
17         1       2
18         0       3
19         1       3
20         0       2
21         1       2
22         1       3
23         1       1
24         0       3
25         1       3
26         0       3
27         0       1
28         1       3
29         0       3
30         0       1

In [ ]:
tt.loc[10:30:4,['survived','pclass']]

    survived  pclass
10         1       3
14         0       3
18         0       3
22         1       3
26         0       3
30         0       1

In [ ]:
tt.iloc[10:30:2,['survived','pclass']]

IndexError: .iloc requires numeric indexers, got ['survived' 'pclass']

In [ ]:
tt

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
tt.iloc[10:30:2,3:9] # 왼쪽에서 4번째 열~9번째 열 / index 10-30 2씩 증가 but 종료 index 제외

     age  sibsp  parch     fare embarked   class
10   4.0      1      1  16.7000        S   Third
12  20.0      0      0   8.0500        S   Third
14  14.0      0      0   7.8542        S   Third
16   2.0      4      1  29.1250        Q   Third
18  31.0      1      0  18.0000        S   Third
20  35.0      0      0  26.0000        S  Second
22  15.0      0      0   8.0292        Q   Third
24   8.0      3      1  21.0750        S   Third
26   NaN      0      0   7.2250        C   Third
28   NaN      0      0   7.8792        Q   Third

In [ ]:
tt.loc[10:30:2, ['survived', 'pclass', 'fare']] # 종료 index 포함

    survived  pclass     fare
10         1       3  16.7000
12         0       3   8.0500
14         0       3   7.8542
16         0       3  29.1250
18         0       3  18.0000
20         0       2  26.0000
22         1       3   8.0292
24         0       3  21.0750
26         0       3   7.2250
28         1       3   7.8792
30         0       1  27.7208

### 방금 위에 배운 loc, iloc 그리고 우리가 처음 배웠던 [] [[]] 컬럼 추출을 응용하자!

In [ ]:
tt[['survived','pclass','sex','fare']].loc[4] # index4 추출

survived       0
pclass         3
sex         male
fare        8.05
Name: 4, dtype: object

In [ ]:
tt['survived'].loc[4]

np.int64(0)

In [ ]:
tt.loc[4][['survived','pclass','sex','fare']]

survived       0
pclass         3
sex         male
fare        8.05
Name: 4, dtype: object

In [ ]:
np.mean(tt['fare'].loc[0:10])

np.float64(26.082563636363634)

In [ ]:
np.mean(tt.loc[0:10, ['fare']])

np.float64(26.082563636363634)

In [ ]:
# index 0부터 10까지의 전체 행을 선택(dataframe 반환) -> 'fare'열을 선택(series 반환)
# np.mean() : series의 평균을 계산 => 결과는 float(단일 숫자)

tt.loc[0:10]['fare']

0      7.2500
1     71.2833
2      7.9250
3     53.1000
4      8.0500
5      8.4583
6     51.8625
7     21.0750
8     11.1333
9     30.0708
10    16.7000
Name: fare, dtype: float64

In [ ]:
# index 0부터 10까지의 'fare' 칼럼을 dataframe 형태로 선택
# np.mean() : dataframe 평균 계산 => 출력값은 float가 아닌 series

tt.loc[0:10, ['fare']]

       fare
0    7.2500
1   71.2833
2    7.9250
3   53.1000
4    8.0500
5    8.4583
6   51.8625
7   21.0750
8   11.1333
9   30.0708
10  16.7000

In [ ]:
#Q. 0부터 10까지의 인덱스 넘버 순서의 승객의 평균 요금을 알려주고, 이 승객들의 생존했는지 여부를 카운팅으로 알려줘!
np.mean(tt.loc[0:10]['fare'])

np.float64(26.082563636363634)

In [ ]:
tt.loc[0:10]['survived'].value_counts()

survived
1    6
0    5
Name: count, dtype: int64

## 데이터 분석에 필요한 기초 문법
- query() 데이터 조건에 따른 추출
- df[df[]] 불린 문법
- sort_values() 정렬
- 파생변수 추가 (assign,lambda) 그 파생변수를 함수를 써서 만들기
- groupby - 요약 집계 -> agg함수 같이 데이터를 집계해서 사용한다.
- merge - 데이터 병합
- str - 문자열 문법
- 기타 (시계열 등등) 특정한 데이터 타입에 따른 문법

## Query
    - 쿼리 내가 원하는 데이터를 추출하기 위해 조건을 질의하는 것
    - 그 조건을 명확하게 문법으로 풀어서 적고 추출하는 것
    - 데이터프레임.query('조건')

In [ ]:
## pclass가 3인 승객을 추출해줘!
## 그런데 여기에 fare 5 이상인 승객을 출력해줘
## 숫자로만 데이터를 추출
tt.query('pclass==3 & fare >= 5')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
tt.query('pclass==3')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
## 문자로 데이터 추출
## sex male인데 여기에 age는 25살 이상으로 추출해줘!
tt.query('sex ==male & age>=25')

UndefinedVariableError: name 'male' is not defined

In [ ]:
tt.query("sex =='male' & age>=25") # 문자열 순서 잘 정리해서 사용하셔야 된다.

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
tt.query("sex =='male' or age>=25")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
tt.query('sex == "male" & age >= 25')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True