In [1]:
# seaborn 패키지를 불러와서 가지고 오기!
import pandas as pd
import seaborn as sns

tt =sns.load_dataset('titanic')

## 데이터 분석에 필요한 기초 문법
- query() 데이터 조건에 따른 추출
- df[df[]] 불린 문법
- sort_values() 정렬
- 파생변수 추가 (assign,lambda) 그 파생변수를 함수를 써서 만들기
- groupby - 요약 집계 -> agg함수 같이 데이터를 집계해서 사용한다.
- merge - 데이터 병합
- str - 문자열 문법
- 기타 (시계열 등등) 특정한 데이터 타입에 따른 문법

In [2]:
tt

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
tt.loc[0]

survived                 0
pclass                   3
sex                   male
age                   22.0
sibsp                    1
parch                    0
fare                  7.25
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                False
Name: 0, dtype: object

### 데이터프레임 문법은 -> 재구조화 될 수 있다. -> 끝이 데이터프레임이면 계속해서 재구조화 할 수 있다.
    - 데이터프레임 문법이 계속 적용된다.

In [4]:
#Q1. 여성이고 age >30 pclass 1등석에 탄 사람의 fare 요금과 여성이고 age >30 pclass 3등석에 탄 사람의 fare 요금 평균 비교하자!

In [5]:
tt.query("age > 30 & sex == 'female' & pclass == 1") # dataframe
tt.query("age > 30 & sex == 'female' & pclass == 1")['fare'] # series

test1 = tt.query("age > 30 & sex == 'female' & pclass == 1")['fare'].mean()
test2 = tt.query("age > 30 & sex == 'female' & pclass == 3")['fare'].mean()

In [6]:
print(test1, test2, test1-test2)

104.72483399999999 19.914313043478256 84.81052095652173

In [7]:
tt.query("age > 30 & sex=='female' & pclass == 1")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
61,1,1,female,38.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
177,0,1,female,50.0,0,0,28.7125,C,First,woman,False,C,Cherbourg,no,True
194,1,1,female,44.0,0,0,27.7208,C,First,woman,False,B,Cherbourg,yes,True
195,1,1,female,58.0,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
215,1,1,female,31.0,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
218,1,1,female,32.0,0,0,76.2917,C,First,woman,False,D,Cherbourg,yes,True
230,1,1,female,35.0,1,0,83.4750,S,First,woman,False,C,Southampton,yes,False
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
268,1,1,female,58.0,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False
269,1,1,female,35.0,0,0,135.6333,S,First,woman,False,C,Southampton,yes,True
275,1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
299,1,1,female,50.0,0,1,247.5208,C,First,woman,False,B,Cherbourg,yes,False
318,1,1,female,31.0,0,2,164.8667,S,First,woman,False,C,Southampton,yes,False
319,1,1,female,40.0,1,1,134.5000,C,First,woman,False,E,Cherbourg,yes,False
325,1,1,female,36.0,0,0,135.6333,C,First,woman,False,C,Cherbourg,yes,True
337,1,1,female,41.0,0,0,134.5000,C,First,woman,False,E,Cherbourg,yes,True
366,1,1,female,60.0,1,0,75.2500,C,First,woman,False,D,Cherbourg,yes,False
380,1,1,female,42.0,0,0,227.5250,C,First,woman,False,NaN,Cherbourg,yes,True
383,1,1,female,35.0,1,0,52.0000,S,First,woman,False,NaN,Southampton,yes,False
412,1,1,female,33.0,1,0,90.0000,Q,First,woman,False,C,Queenstown,yes,False
486,1,1,female,35.0,1,0,90.0000,S,First,woman,False,C,Southampton,yes,False
496,1,1,female,54.0,1,0,78.2667,C,First,woman,False,D,Cherbourg,yes,False
513,1,1,female,54.0,1,0,59.4000,C,First,woman,False,NaN,Cherbourg,yes,False
523,1,1,female,44.0,0,1,57.9792,C,First,woman,False,B,Cherbourg,yes,False
540,1,1,female,36.0,0,2,71.0000,S,First,woman,False,B,Southampton,yes,False
556,1,1,female,48.0,1,0,39.6000,C,First,woman,False,A,Cherbourg,yes,False
558,1,1,female,39.0,1,1,79.6500,S,First,woman,False,E,Southampton,yes,False
571,1,1,female,53.0,2,0,51.4792,S,First,woman,False,C,Southampton,yes,False
577,1,1,female,39.0,1,0,55.9000,S,First,woman,False,E,Southampton,yes,False
581,1,1,female,39.0,1,1,110.8833,C,First,woman,False,C,Cherbourg,yes,False
591,1,1,female,52.0,1,0,78.2667,C,First,woman,False,D,Cherbourg,yes,False
609,1,1,female,40.0,0,0,153.4625,S,First,woman,False,C,Southampton,yes,True
716,1,1,female,38.0,0,0,227.5250,C,First,woman,False,C,Cherbourg,yes,True
759,1,1,female,33.0,0,0,86.5000,S,First,woman,False,B,Southampton,yes,True
763,1,1,female,36.0,1,2,120.0000,S,First,woman,False,B,Southampton,yes,False
765,1,1,female,51.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
779,1,1,female,43.0,0,1,211.3375,S,First,woman,False,B,Southampton,yes,False
796,1,1,female,49.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
809,1,1,female,33.0,1,0,53.1000,S,First,woman,False,E,Southampton,yes,False
820,1,1,female,52.0,1,1,93.5000,S,First,woman,False,B,Southampton,yes,False
829,1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
835,1,1,female,39.0,1,1,83.1583,C,First,woman,False,E,Cherbourg,yes,False
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False

In [8]:
## 추가적인 샘플링
## 15명을 샘플링하겠다.

tt.query("age > 30 & sex=='female' & pclass == 1").loc[0:15] # index 0~15에 포함된 "age > 30 & sex=='female' & pclass == 1" 출력

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True

In [9]:
tt.query("age > 30 & sex=='female' & pclass == 1").iloc[0:15] # "age > 30 & sex=='female' & pclass == 1" 만족하는 15개 출력

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
61,1,1,female,38.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
177,0,1,female,50.0,0,0,28.7125,C,First,woman,False,C,Cherbourg,no,True
194,1,1,female,44.0,0,0,27.7208,C,First,woman,False,B,Cherbourg,yes,True
195,1,1,female,58.0,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
215,1,1,female,31.0,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
218,1,1,female,32.0,0,0,76.2917,C,First,woman,False,D,Cherbourg,yes,True
230,1,1,female,35.0,1,0,83.4750,S,First,woman,False,C,Southampton,yes,False
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
268,1,1,female,58.0,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False
269,1,1,female,35.0,0,0,135.6333,S,First,woman,False,C,Southampton,yes,True
275,1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False

In [10]:
tt.query("age > 30 & sex=='female' & pclass == 1")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
61,1,1,female,38.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
177,0,1,female,50.0,0,0,28.7125,C,First,woman,False,C,Cherbourg,no,True
194,1,1,female,44.0,0,0,27.7208,C,First,woman,False,B,Cherbourg,yes,True
195,1,1,female,58.0,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
215,1,1,female,31.0,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
218,1,1,female,32.0,0,0,76.2917,C,First,woman,False,D,Cherbourg,yes,True
230,1,1,female,35.0,1,0,83.4750,S,First,woman,False,C,Southampton,yes,False
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
268,1,1,female,58.0,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False
269,1,1,female,35.0,0,0,135.6333,S,First,woman,False,C,Southampton,yes,True
275,1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
299,1,1,female,50.0,0,1,247.5208,C,First,woman,False,B,Cherbourg,yes,False
318,1,1,female,31.0,0,2,164.8667,S,First,woman,False,C,Southampton,yes,False
319,1,1,female,40.0,1,1,134.5000,C,First,woman,False,E,Cherbourg,yes,False
325,1,1,female,36.0,0,0,135.6333,C,First,woman,False,C,Cherbourg,yes,True
337,1,1,female,41.0,0,0,134.5000,C,First,woman,False,E,Cherbourg,yes,True
366,1,1,female,60.0,1,0,75.2500,C,First,woman,False,D,Cherbourg,yes,False
380,1,1,female,42.0,0,0,227.5250,C,First,woman,False,NaN,Cherbourg,yes,True
383,1,1,female,35.0,1,0,52.0000,S,First,woman,False,NaN,Southampton,yes,False
412,1,1,female,33.0,1,0,90.0000,Q,First,woman,False,C,Queenstown,yes,False
486,1,1,female,35.0,1,0,90.0000,S,First,woman,False,C,Southampton,yes,False
496,1,1,female,54.0,1,0,78.2667,C,First,woman,False,D,Cherbourg,yes,False
513,1,1,female,54.0,1,0,59.4000,C,First,woman,False,NaN,Cherbourg,yes,False
523,1,1,female,44.0,0,1,57.9792,C,First,woman,False,B,Cherbourg,yes,False
540,1,1,female,36.0,0,2,71.0000,S,First,woman,False,B,Southampton,yes,False
556,1,1,female,48.0,1,0,39.6000,C,First,woman,False,A,Cherbourg,yes,False
558,1,1,female,39.0,1,1,79.6500,S,First,woman,False,E,Southampton,yes,False
571,1,1,female,53.0,2,0,51.4792,S,First,woman,False,C,Southampton,yes,False
577,1,1,female,39.0,1,0,55.9000,S,First,woman,False,E,Southampton,yes,False
581,1,1,female,39.0,1,1,110.8833,C,First,woman,False,C,Cherbourg,yes,False
591,1,1,female,52.0,1,0,78.2667,C,First,woman,False,D,Cherbourg,yes,False
609,1,1,female,40.0,0,0,153.4625,S,First,woman,False,C,Southampton,yes,True
716,1,1,female,38.0,0,0,227.5250,C,First,woman,False,C,Cherbourg,yes,True
759,1,1,female,33.0,0,0,86.5000,S,First,woman,False,B,Southampton,yes,True
763,1,1,female,36.0,1,2,120.0000,S,First,woman,False,B,Southampton,yes,False
765,1,1,female,51.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
779,1,1,female,43.0,0,1,211.3375,S,First,woman,False,B,Southampton,yes,False
796,1,1,female,49.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
809,1,1,female,33.0,1,0,53.1000,S,First,woman,False,E,Southampton,yes,False
820,1,1,female,52.0,1,1,93.5000,S,First,woman,False,B,Southampton,yes,False
829,1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
835,1,1,female,39.0,1,1,83.1583,C,First,woman,False,E,Cherbourg,yes,False
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False

### 불린값 추출

- df[df[]] 불린 문법
- df[True] = 참값이 출력이된다
- True 조건을 만들고 데이터프레임으로 추출하면 -> 해당 기준의 값들이 추출된다.
- df[df['조건1']], 조건 1이 참인 값들이 추출이 된다.
- 다중조건인 경우?
- df[df[(조건1)&(조건2)...&(조건n)]]

In [11]:
# 불린값 추출

tt['age'] > 30

0      False
1       True
2      False
3       True
4       True
       ...
886    False
887    False
888    False
889    False
890     True
Name: age, Length: 891, dtype: bool

In [12]:
# df[df[...]] ...을 만족하는 값이 True인 정보들 출력

tt[tt['age'] > 30]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [13]:
## 2개의 조건
## 2개 같은 기준으로 출력된 문법

print(tt.query("age > 30 & sex=='female' & pclass == 1")['fare'].mean())
print(tt[(tt['age']>30) & (tt['sex']=='female')& (tt['pclass']==1)]['fare'].mean())

104.72483399999999
104.72483399999999

In [14]:
print(tt.query("age > 30 & sex =='female' & pclass == 1")['fare'].mean())

104.72483399999999

In [15]:
print(tt[(tt['age'] > 30) & (tt['sex'] == 'female') & (tt['pclass'] == 1)]['fare'].mean())

104.72483399999999

- sort_values() 정렬
    - 내림차순, 오름차순
    - sort_values('컬럼1') 오름차순 디폴트 정렬
        - 마지막에 na매핑된다.
    - tt.sort_values('age', ascending=False) 내림차순
    
    - 두 가지의 이상으로 정렬하는 경우 첫 번째 있는 컬럼이 1순위, 2순위 작동 ( 단 1순위가 동일한 값인 경우 )

In [16]:
tt.sort_values('pclass')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
839,1,1,male,NaN,0,0,29.7000,C,First,man,True,C,Cherbourg,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False

In [17]:
tt.sort_values('survived')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False

In [18]:
tt.sort_values('sex')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
383,1,1,female,35.0,1,0,52.0000,S,First,woman,False,NaN,Southampton,yes,False
218,1,1,female,32.0,0,0,76.2917,C,First,woman,False,D,Cherbourg,yes,True
609,1,1,female,40.0,0,0,153.4625,S,First,woman,False,C,Southampton,yes,True
216,1,3,female,27.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
215,1,1,female,31.0,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371,0,3,male,18.0,1,0,6.4958,S,Third,man,True,NaN,Southampton,no,False
372,0,3,male,19.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
373,0,1,male,22.0,0,0,135.6333,C,First,man,True,NaN,Cherbourg,no,True
360,0,3,male,40.0,1,4,27.9000,S,Third,man,True,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [19]:
tt.sort_values('age')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [21]:
tt.sort_values('age', ascending=False) # 내림차순

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [20]:
tt.sort_values(['age','fare']) # age, fare 오름차순

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,1,1,female,NaN,0,0,110.8833,C,First,woman,False,NaN,Cherbourg,yes,True
334,1,1,female,NaN,1,0,133.6500,S,First,woman,False,NaN,Southampton,yes,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
527,0,1,male,NaN,0,0,221.7792,S,First,man,True,C,Southampton,no,True
557,0,1,male,NaN,0,0,227.5250,C,First,man,True,NaN,Cherbourg,no,True

In [22]:
tt.sort_values(['age','fare'], ascending=[False,True]) # age 내림차순, fare 오름차순 (age가 우선순위)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,1,1,female,NaN,0,0,110.8833,C,First,woman,False,NaN,Cherbourg,yes,True
334,1,1,female,NaN,1,0,133.6500,S,First,woman,False,NaN,Southampton,yes,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
527,0,1,male,NaN,0,0,221.7792,S,First,man,True,C,Southampton,no,True
557,0,1,male,NaN,0,0,227.5250,C,First,man,True,NaN,Cherbourg,no,True

In [23]:
tt.sort_values(['age','fare'], ascending=[False,False]) # age 내림차순, fare 내림차순

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
633,0,1,male,NaN,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True
674,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
732,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
815,0,1,male,NaN,0,0,0.0000,S,First,man,True,B,Southampton,no,True

- 파생변수 추가 (assign,lambda) 그 파생변수를 함수를 써서 만들기
- assign 함수를 통해 파생변수 만들기
- df.assign(변수명 = 내가 원하는 파생변수식)
- 여러 변수를 한 번에 만들 수 있다.
- df.assign((변수명1 = 내가 원하는 파생변수식1), (변수명2 = 내가 원하는 파생변수식2))
- df.assign(변수명1 = lambda 식으로 파생변수 만들기 )

In [24]:
## 요금 + age 파생변수로 만들기

tt['age+fare']= tt['age'] + tt['fare']

In [27]:
tt.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age+fare
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,29.2500
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,109.2833
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,33.9250
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,88.1000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,43.0500

In [28]:
tt.assign(agefare1 = tt['age'] + tt['fare'],
         agefare2 = tt['age'] - tt['fare'],)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age+fare,agefare1,agefare2
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,29.2500,29.2500,14.7500
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,109.2833,109.2833,-33.2833
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,33.9250,33.9250,18.0750
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,88.1000,88.1000,-18.1000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,43.0500,43.0500,26.9500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,40.0000,40.0000,14.0000
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,49.0000,49.0000,-11.0000
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN,NaN,NaN
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,56.0000,56.0000,-4.0000
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,39.7500,39.7500,24.2500

In [30]:
import numpy as np

tt.assign(seg_20 = np.where(tt['age']>20, 'seg_20','others'))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age+fare,seg_20
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,29.2500,seg_20
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,109.2833,seg_20
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,33.9250,seg_20
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,88.1000,seg_20
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,43.0500,seg_20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,40.0000,seg_20
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,49.0000,others
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN,others
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,56.0000,seg_20
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,39.7500,seg_20

In [31]:
##lambda를 사용해서도 할 수 있다.

tt.assign(age_fare= lambda x:x['age']+x['fare'])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age+fare,age_fare
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,29.2500,29.2500
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,109.2833,109.2833
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,33.9250,33.9250
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,88.1000,88.1000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,43.0500,43.0500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,40.0000,40.0000
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,49.0000,49.0000
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN,NaN
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,56.0000,56.0000
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,39.7500,39.7500

In [32]:
tt[['sex','age','fare']]

        sex   age     fare
0      male  22.0   7.2500
1    female  38.0  71.2833
2    female  26.0   7.9250
3    female  35.0  53.1000
4      male  35.0   8.0500
..      ...   ...      ...
886    male  27.0  13.0000
887  female  19.0  30.0000
888  female   NaN  23.4500
889    male  26.0  30.0000
890    male  32.0   7.7500

[891 rows x 3 columns]

- groupby - 요약 집계 -> agg함수 같이 데이터를 집계해서 사용한다.
    - 데이터를 요약할 때 많이 사용하실 것
    - sex에 따른 age, fare
    - male - age , fare 집계할 수 있다. -> 요약통계치가 필요하다. 통계함수랑 같이 많이 사용한다.
    - female - age, fare 집계할 수 있다. -> 요약통계치가 필요하다. 통계함수랑 같이 많이 사용한다.
    
- 데이터프레임.groupby(그룹을묶을 컬럼)
- 내가 원하는 그룹의 데이터프레임만 추출
    - 데이터프레임.get_group(내가 그룹바이한 컬럼의 값으로 추출 e.g. pclass면 1,2,3 으로 추출)
----
- 2개 이상으로 그룹 묶는 경우
- 데이터프레임.groupby(['컬럼1','컬럼2'])

----
- 내가 원하는 컬럼을 추출해서 -> grouby로 요약 통계치를 만들자!
- 전체 데이터프레임에서 내가 원하는 데이터만 추출하는 동시에 같이 groupby를 사용하는 것

----
- 여러 개의 통계치를 볼 때 agg함수를 같이 사용해서 진행한다.

- 데이터프레임.groupby('컬럼1').agg(내가원하는 파생변수 명 = ('집계하고 싶은 컬럼1',' 집계하고 싶은 통계치1'), ('집계하고 싶은 컬럼2',' 집계하고 싶은 통계치2'),
-----
- 우리가 원하는 함수를 만들어서 agg함수에 대입시킬 수 있다.

In [39]:
tt_sex = tt.groupby('sex')
tt_sex # DataFrameGroupBy 객체

In [40]:
for i,j in tt_sex:
    print(i)        # female, male
    print(j)        # i에 해당하는 datarame

female
     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
8           1       3  female  27.0      0      2  11.1333        S   Third
9           1       2  female  14.0      1      0  30.0708        C  Second
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
880         1       2  female  25.0      0      1  26.0000        S  Second
882         0       3  female  22.0      0      0  10.5167        S   Third
885         0       3  female  39.0      0      5  29.1250        Q   Third
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third

       who  adult_male deck  embark_town alive  alone  age+fare
1    woman       False    C    Cherbourg   yes  False  109.2833
2    woman       False  NaN  Southampton   yes   True   33.9250
3    woman       False    C  Southampton   yes  False   88.1000
8    woman       False  NaN  Southampton   yes  False   38.1333
9    child       False  NaN    Cherbourg   yes  False   44.0708
..     ...         ...  ...          ...   ...    ...       ...
880  woman       False  NaN  Southampton   yes  False   51.0000
882  woman       False  NaN  Southampton    no   True   32.5167
885  woman       False  NaN   Queenstown    no  False   68.1250
887  woman       False    B  Southampton   yes   True   49.0000
888  woman       False  NaN  Southampton    no  False       NaN

[314 rows x 16 columns]
male
     survived  pclass   sex   age  sibsp  parch     fare embarked   class  \
0           0       3  male  22.0      1      0   7.2500        S   Third
4           0       3  male  35.0      0      0   8.0500        S   Third
5           0       3  male   NaN      0      0   8.4583        Q   Third
6           0       1  male  54.0      0      0  51.8625        S   First
7           0       3  male   2.0      3      1  21.0750        S   Third
..        ...     ...   ...   ...    ...    ...      ...      ...     ...
883         0       2  male  28.0      0      0  10.5000        S  Second
884         0       3  male  25.0      0      0   7.0500        S   Third
886         0       2  male  27.0      0      0  13.0000        S  Second
889         1       1  male  26.0      0      0  30.0000        C   First
890         0       3  male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone  age+fare
0      man        True  NaN  Southampton    no  False   29.2500
4      man        True  NaN  Southampton    no   True   43.0500
5      man        True  NaN   Queenstown    no   True       NaN
6      man        True    E  Southampton    no   True  105.8625
7    child       False  NaN  Southampton    no  False   23.0750
..     ...         ...  ...          ...   ...    ...       ...
883    man        True  NaN  Southampton    no   True   38.5000
884    man        True  NaN  Southampton    no   True   32.0500
886    man        True  NaN  Southampton    no   True   40.0000
889    man        True    C    Cherbourg   yes   True   56.0000
890    man        True  NaN   Queenstown    no   True   39.7500

[577 rows x 16 columns]

In [41]:
tt_pclass  = tt.groupby('pclass')

In [42]:
for i,j in tt_pclass:
    print(i)
    print(j)

1
     survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1           1       1  female  38.0      1      0  71.2833        C  First
3           1       1  female  35.0      1      0  53.1000        S  First
6           0       1    male  54.0      0      0  51.8625        S  First
11          1       1  female  58.0      0      0  26.5500        S  First
23          1       1    male  28.0      0      0  35.5000        S  First
..        ...     ...     ...   ...    ...    ...      ...      ...    ...
871         1       1  female  47.0      1      1  52.5542        S  First
872         0       1    male  33.0      0      0   5.0000        S  First
879         1       1  female  56.0      0      1  83.1583        C  First
887         1       1  female  19.0      0      0  30.0000        S  First
889         1       1    male  26.0      0      0  30.0000        C  First

       who  adult_male deck  embark_town alive  alone  age+fare
1    woman       False    C    Cherbourg   yes  False  109.2833
3    woman       False    C  Southampton   yes  False   88.1000
6      man        True    E  Southampton    no   True  105.8625
11   woman       False    C  Southampton   yes   True   84.5500
23     man        True    A  Southampton   yes   True   63.5000
..     ...         ...  ...          ...   ...    ...       ...
871  woman       False    D  Southampton   yes  False   99.5542
872    man        True    B  Southampton    no   True   38.0000
879  woman       False    C    Cherbourg   yes  False  139.1583
887  woman       False    B  Southampton   yes   True   49.0000
889    man        True    C    Cherbourg   yes   True   56.0000

[216 rows x 16 columns]
2
     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
9           1       2  female  14.0      1      0  30.0708        C  Second
15          1       2  female  55.0      0      0  16.0000        S  Second
17          1       2    male   NaN      0      0  13.0000        S  Second
20          0       2    male  35.0      0      0  26.0000        S  Second
21          1       2    male  34.0      0      0  13.0000        S  Second
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
866         1       2  female  27.0      1      0  13.8583        C  Second
874         1       2  female  28.0      1      0  24.0000        C  Second
880         1       2  female  25.0      0      1  26.0000        S  Second
883         0       2    male  28.0      0      0  10.5000        S  Second
886         0       2    male  27.0      0      0  13.0000        S  Second

       who  adult_male deck  embark_town alive  alone  age+fare
9    child       False  NaN    Cherbourg   yes  False   44.0708
15   woman       False  NaN  Southampton   yes   True   71.0000
17     man        True  NaN  Southampton   yes   True       NaN
20     man        True  NaN  Southampton    no   True   61.0000
21     man        True    D  Southampton   yes   True   47.0000
..     ...         ...  ...          ...   ...    ...       ...
866  woman       False  NaN    Cherbourg   yes  False   40.8583
874  woman       False  NaN    Cherbourg   yes  False   52.0000
880  woman       False  NaN  Southampton   yes  False   51.0000
883    man        True  NaN  Southampton    no   True   38.5000
886    man        True  NaN  Southampton    no   True   40.0000

[184 rows x 16 columns]
3
     survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0           0       3    male  22.0      1      0   7.2500        S  Third
2           1       3  female  26.0      0      0   7.9250        S  Third
4           0       3    male  35.0      0      0   8.0500        S  Third
5           0       3    male   NaN      0      0   8.4583        Q  Third
7           0       3    male   2.0      3      1  21.0750        S  Third
..        ...     ...     ...   ...    ...    ...      ...      ...    ...
882         0       3  female  22.0      0      0  10.5167        S  Third
884         0       3    male  25.0      0      0   7.0500        S  Third
885         0       3  female  39.0      0      5  29.1250        Q  Third
888         0       3  female   NaN      1      2  23.4500        S  Third
890         0       3    male  32.0      0      0   7.7500        Q  Third

       who  adult_male deck  embark_town alive  alone  age+fare
0      man        True  NaN  Southampton    no  False   29.2500
2    woman       False  NaN  Southampton   yes   True   33.9250
4      man        True  NaN  Southampton    no   True   43.0500
5      man        True  NaN   Queenstown    no   True       NaN
7    child       False  NaN  Southampton    no  False   23.0750
..     ...         ...  ...          ...   ...    ...       ...
882  woman       False  NaN  Southampton    no   True   32.5167
884    man        True  NaN  Southampton    no   True   32.0500
885  woman       False  NaN   Queenstown    no  False   68.1250
888  woman       False  NaN  Southampton    no  False       NaN
890    man        True  NaN   Queenstown    no   True   39.7500

[491 rows x 16 columns]

In [44]:
tt_pclass.get_group(1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age+fare
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,109.2833
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,88.1000
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,105.8625
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,84.5500
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True,63.5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False,99.5542
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True,38.0000
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,139.1583
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,49.0000
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,56.0000

In [45]:
tt_pclass.get_group(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age+fare
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False,44.0708
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True,71.0000
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True,NaN
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True,61.0000
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True,47.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
866,1,2,female,27.0,1,0,13.8583,C,Second,woman,False,NaN,Cherbourg,yes,False,40.8583
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False,52.0000
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False,51.0000
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True,38.5000
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,40.0000

In [46]:
tt_pclass.get_group(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age+fare
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,29.2500
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,33.9250
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,43.0500
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True,NaN
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False,23.0750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True,32.5167
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True,32.0500
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False,68.1250
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,39.7500

In [47]:
tt_sex.get_group('female')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age+fare
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,109.2833
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,33.9250
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,88.1000
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False,38.1333
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False,44.0708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False,51.0000
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True,32.5167
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False,68.1250
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,49.0000
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN

In [48]:
tt_sex.get_group('male')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age+fare
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,29.2500
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,43.0500
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True,NaN
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,105.8625
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False,23.0750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True,38.5000
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True,32.0500
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,40.0000
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,56.0000
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,39.7500

In [50]:
## 성별에 따른 클래스 들의 요금의 평균
## male 1,2,3 요금 평균들
## female 1,2,3 요금 평균들

tt_sp=tt.groupby(['sex','pclass'])

In [51]:
for i,j in tt_sp:
    print(i)      # 2*3, 6개의 조합
    print(j)      # i에 따른 dataframe 출력

('female', np.int64(1))
     survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
1           1       1  female  38.0      1      0   71.2833        C  First
3           1       1  female  35.0      1      0   53.1000        S  First
11          1       1  female  58.0      0      0   26.5500        S  First
31          1       1  female   NaN      1      0  146.5208        C  First
52          1       1  female  49.0      1      0   76.7292        C  First
..        ...     ...     ...   ...    ...    ...       ...      ...    ...
856         1       1  female  45.0      1      1  164.8667        S  First
862         1       1  female  48.0      0      0   25.9292        S  First
871         1       1  female  47.0      1      1   52.5542        S  First
879         1       1  female  56.0      0      1   83.1583        C  First
887         1       1  female  19.0      0      0   30.0000        S  First

       who  adult_male deck  embark_town alive  alone  age+fare
1    woman       False    C    Cherbourg   yes  False  109.2833
3    woman       False    C  Southampton   yes  False   88.1000
11   woman       False    C  Southampton   yes   True   84.5500
31   woman       False    B    Cherbourg   yes  False       NaN
52   woman       False    D    Cherbourg   yes  False  125.7292
..     ...         ...  ...          ...   ...    ...       ...
856  woman       False  NaN  Southampton   yes  False  209.8667
862  woman       False    D  Southampton   yes   True   73.9292
871  woman       False    D  Southampton   yes  False   99.5542
879  woman       False    C    Cherbourg   yes  False  139.1583
887  woman       False    B  Southampton   yes   True   49.0000

[94 rows x 16 columns]
('female', np.int64(2))
     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
9           1       2  female  14.0      1      0  30.0708        C  Second
15          1       2  female  55.0      0      0  16.0000        S  Second
41          0       2  female  27.0      1      0  21.0000        S  Second
43          1       2  female   3.0      1      2  41.5792        C  Second
53          1       2  female  29.0      1      0  26.0000        S  Second
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
854         0       2  female  44.0      1      0  26.0000        S  Second
865         1       2  female  42.0      0      0  13.0000        S  Second
866         1       2  female  27.0      1      0  13.8583        C  Second
874         1       2  female  28.0      1      0  24.0000        C  Second
880         1       2  female  25.0      0      1  26.0000        S  Second

       who  adult_male deck  embark_town alive  alone  age+fare
9    child       False  NaN    Cherbourg   yes  False   44.0708
15   woman       False  NaN  Southampton   yes   True   71.0000
41   woman       False  NaN  Southampton    no  False   48.0000
43   child       False  NaN    Cherbourg   yes  False   44.5792
53   woman       False  NaN  Southampton   yes  False   55.0000
..     ...         ...  ...          ...   ...    ...       ...
854  woman       False  NaN  Southampton    no  False   70.0000
865  woman       False  NaN  Southampton   yes   True   55.0000
866  woman       False  NaN    Cherbourg   yes  False   40.8583
874  woman       False  NaN    Cherbourg   yes  False   52.0000
880  woman       False  NaN  Southampton   yes  False   51.0000

[76 rows x 16 columns]
('female', np.int64(3))
     survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
2           1       3  female  26.0      0      0   7.9250        S  Third
8           1       3  female  27.0      0      2  11.1333        S  Third
10          1       3  female   4.0      1      1  16.7000        S  Third
14          0       3  female  14.0      0      0   7.8542        S  Third
18          0       3  female  31.0      1      0  18.0000        S  Third
..        ...     ...     ...   ...    ...    ...      ...      ...    ...
863         0       3  female   NaN      8      2  69.5500        S  Third
875         1       3  female  15.0      0      0   7.2250        C  Third
882         0       3  female  22.0      0      0  10.5167        S  Third
885         0       3  female  39.0      0      5  29.1250        Q  Third
888         0       3  female   NaN      1      2  23.4500        S  Third

       who  adult_male deck  embark_town alive  alone  age+fare
2    woman       False  NaN  Southampton   yes   True   33.9250
8    woman       False  NaN  Southampton   yes  False   38.1333
10   child       False    G  Southampton   yes  False   20.7000
14   child       False  NaN  Southampton    no   True   21.8542
18   woman       False  NaN  Southampton    no  False   49.0000
..     ...         ...  ...          ...   ...    ...       ...
863  woman       False  NaN  Southampton    no  False       NaN
875  child       False  NaN    Cherbourg   yes   True   22.2250
882  woman       False  NaN  Southampton    no   True   32.5167
885  woman       False  NaN   Queenstown    no  False   68.1250
888  woman       False  NaN  Southampton    no  False       NaN

[144 rows x 16 columns]
('male', np.int64(1))
     survived  pclass   sex   age  sibsp  parch      fare embarked  class  \
6           0       1  male  54.0      0      0   51.8625        S  First
23          1       1  male  28.0      0      0   35.5000        S  First
27          0       1  male  19.0      3      2  263.0000        S  First
30          0       1  male  40.0      0      0   27.7208        C  First
34          0       1  male  28.0      1      0   82.1708        C  First
..        ...     ...   ...   ...    ...    ...       ...      ...    ...
839         1       1  male   NaN      0      0   29.7000        C  First
857         1       1  male  51.0      0      0   26.5500        S  First
867         0       1  male  31.0      0      0   50.4958        S  First
872         0       1  male  33.0      0      0    5.0000        S  First
889         1       1  male  26.0      0      0   30.0000        C  First

     who  adult_male deck  embark_town alive  alone  age+fare
6    man        True    E  Southampton    no   True  105.8625
23   man        True    A  Southampton   yes   True   63.5000
27   man        True    C  Southampton    no  False  282.0000
30   man        True  NaN    Cherbourg    no   True   67.7208
34   man        True  NaN    Cherbourg    no  False  110.1708
..   ...         ...  ...          ...   ...    ...       ...
839  man        True    C    Cherbourg   yes   True       NaN
857  man        True    E  Southampton   yes   True   77.5500
867  man        True    A  Southampton    no   True   81.4958
872  man        True    B  Southampton    no   True   38.0000
889  man        True    C    Cherbourg   yes   True   56.0000

[122 rows x 16 columns]
('male', np.int64(2))
     survived  pclass   sex   age  sibsp  parch  fare embarked   class  who  \
17          1       2  male   NaN      0      0  13.0        S  Second  man
20          0       2  male  35.0      0      0  26.0        S  Second  man
21          1       2  male  34.0      0      0  13.0        S  Second  man
33          0       2  male  66.0      0      0  10.5        S  Second  man
70          0       2  male  32.0      0      0  10.5        S  Second  man
..        ...     ...   ...   ...    ...    ...   ...      ...     ...  ...
848         0       2  male  28.0      0      1  33.0        S  Second  man
861         0       2  male  21.0      1      0  11.5        S  Second  man
864         0       2  male  24.0      0      0  13.0        S  Second  man
883         0       2  male  28.0      0      0  10.5        S  Second  man
886         0       2  male  27.0      0      0  13.0        S  Second  man

     adult_male deck  embark_town alive  alone  age+fare
17         True  NaN  Southampton   yes   True       NaN
20         True  NaN  Southampton    no   True      61.0
21         True    D  Southampton   yes   True      47.0
33         True  NaN  Southampton    no   True      76.5
70         True  NaN  Southampton    no   True      42.5
..          ...  ...          ...   ...    ...       ...
848        True  NaN  Southampton    no  False      61.0
861        True  NaN  Southampton    no  False      32.5
864        True  NaN  Southampton    no   True      37.0
883        True  NaN  Southampton    no   True      38.5
886        True  NaN  Southampton    no   True      40.0

[108 rows x 16 columns]
('male', np.int64(3))
     survived  pclass   sex   age  sibsp  parch     fare embarked  class  \
0           0       3  male  22.0      1      0   7.2500        S  Third
4           0       3  male  35.0      0      0   8.0500        S  Third
5           0       3  male   NaN      0      0   8.4583        Q  Third
7           0       3  male   2.0      3      1  21.0750        S  Third
12          0       3  male  20.0      0      0   8.0500        S  Third
..        ...     ...   ...   ...    ...    ...      ...      ...    ...
877         0       3  male  19.0      0      0   7.8958        S  Third
878         0       3  male   NaN      0      0   7.8958        S  Third
881         0       3  male  33.0      0      0   7.8958        S  Third
884         0       3  male  25.0      0      0   7.0500        S  Third
890         0       3  male  32.0      0      0   7.7500        Q  Third

       who  adult_male deck  embark_town alive  alone  age+fare
0      man        True  NaN  Southampton    no  False   29.2500
4      man        True  NaN  Southampton    no   True   43.0500
5      man        True  NaN   Queenstown    no   True       NaN
7    child       False  NaN  Southampton    no  False   23.0750
12     man        True  NaN  Southampton    no   True   28.0500
..     ...         ...  ...          ...   ...    ...       ...
877    man        True  NaN  Southampton    no   True   26.8958
878    man        True  NaN  Southampton    no   True       NaN
881    man        True  NaN  Southampton    no   True   40.8958
884    man        True  NaN  Southampton    no   True   32.0500
890    man        True  NaN   Queenstown    no   True   39.7500

[347 rows x 16 columns]

In [52]:
tt_sp.get_group(('male', 3))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age+fare
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,29.2500
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,43.0500
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True,NaN
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False,23.0750
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,28.0500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,26.8958
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,NaN
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,40.8958
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True,32.0500
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,39.7500

In [54]:
tt.query("sex == 'male' & pclass == 3")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age+fare
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,29.2500
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,43.0500
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True,NaN
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False,23.0750
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,28.0500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,26.8958
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,NaN
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,40.8958
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True,32.0500
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,39.7500

In [55]:
tt[['sex','fare']]

        sex     fare
0      male   7.2500
1    female  71.2833
2    female   7.9250
3    female  53.1000
4      male   8.0500
..      ...      ...
886    male  13.0000
887  female  30.0000
888  female  23.4500
889    male  30.0000
890    male   7.7500

[891 rows x 2 columns]

In [57]:
tt_sf = tt[['sex','fare']].groupby('sex')

In [58]:
for i,j in tt_sf:
  print(i)
  print(j)

female
        sex     fare
1    female  71.2833
2    female   7.9250
3    female  53.1000
8    female  11.1333
9    female  30.0708
..      ...      ...
880  female  26.0000
882  female  10.5167
885  female  29.1250
887  female  30.0000
888  female  23.4500

[314 rows x 2 columns]
male
      sex     fare
0    male   7.2500
4    male   8.0500
5    male   8.4583
6    male  51.8625
7    male  21.0750
..    ...      ...
883  male  10.5000
884  male   7.0500
886  male  13.0000
889  male  30.0000
890  male   7.7500

[577 rows x 2 columns]

In [59]:
tt[['sex','fare']].groupby('sex').max()

            fare
sex
female  512.3292
male    512.3292

In [60]:
test1 =tt[['sex','fare']]

In [61]:
test1.groupby('sex').max()

            fare
sex
female  512.3292
male    512.3292

- 성별과 pclass 따라서 요금의 평균을 알고 싶어!

In [63]:
ttt_sp = tt[['sex', 'pclass', 'fare']]
ttt_sp.groupby(['sex', 'pclass']).mean()

                     fare
sex    pclass
female 1       106.125798
       2        21.970121
       3        16.118810
male   1        67.226127
       2        19.741782
       3        12.661633

In [64]:
tt[['sex','pclass','fare']].groupby(['sex','pclass']).mean()

                     fare
sex    pclass
female 1       106.125798
       2        21.970121
       3        16.118810
male   1        67.226127
       2        19.741782
       3        12.661633

In [65]:
tt[['sex','pclass','fare']].groupby(['pclass','sex']).mean()

                     fare
pclass sex
1      female  106.125798
       male     67.226127
2      female   21.970121
       male     19.741782
3      female   16.118810
       male     12.661633

In [67]:
tt.groupby('pclass').agg(fare_mean =('fare','mean'),
                        fare_sum = ('fare','sum'),
                        fare_max = ('fare','max'),
                        fare_median = ('fare','median'))

        fare_mean    fare_sum  fare_max  fare_median
pclass
1       84.154687  18177.4125  512.3292      60.2875
2       20.662183   3801.8417   73.5000      14.2500
3       13.675550   6714.6951   69.5500       8.0500

In [66]:
tt.groupby(['sex','pclass']).agg(fare_mean =('fare','mean'),
                        fare_sum = ('fare','sum'),
                        fare_max = ('fare','max'),
                        fare_median = ('fare','median'),
                        fare_count = ('fare','count')) # count 카운팅의 개념

                fare_mean   fare_sum  fare_max  fare_median  fare_count
sex    pclass
female 1       106.125798  9975.8250  512.3292     82.66455          94
       2        21.970121  1669.7292   65.0000     22.00000          76
       3        16.118810  2321.1086   69.5500     12.47500         144
male   1        67.226127  8201.5875  512.3292     41.26250         122
       2        19.741782  2132.1125   73.5000     13.00000         108
       3        12.661633  4393.5865   69.5500      7.92500         347

In [68]:
tt.groupby('pclass').agg(age_mean = ('age', 'mean'), age_max = ('age', 'max'))

         age_mean  age_max
pclass
1       38.233441     80.0
2       29.877630     70.0
3       25.140620     74.0

In [69]:
def mean_median(x):
    return x.mean()- x.median()

In [71]:
## 특정 컬럼을 바로 추출해서 위의 함수를 적용시키는 것

tt.groupby('pclass')['fare'].agg(mean_median)  # fare.mean - fare.median

pclass
1    23.867188
2     6.412183
3     5.625550
Name: fare, dtype: float64

In [ ]:
tt[tt['pclass']==1]['fare'].mean()

84.1546875

In [72]:
tt[tt['pclass']==1]['fare'].median()

60.287499999999994

In [73]:
tt[tt['pclass']==1]['fare'].mean() - tt[tt['pclass']==1]['fare'].median()

np.float64(23.8671875)

In [75]:
dd = tt.groupby('pclass')['fare']

In [78]:
for i in dd:
  print(i)

(1, 1      71.2833
3      53.1000
6      51.8625
11     26.5500
23     35.5000
        ...
871    52.5542
872     5.0000
879    83.1583
887    30.0000
889    30.0000
Name: fare, Length: 216, dtype: float64)
(2, 9      30.0708
15     16.0000
17     13.0000
20     26.0000
21     13.0000
        ...
866    13.8583
874    24.0000
880    26.0000
883    10.5000
886    13.0000
Name: fare, Length: 184, dtype: float64)
(3, 0       7.2500
2       7.9250
4       8.0500
5       8.4583
7      21.0750
        ...
882    10.5167
884     7.0500
885    29.1250
888    23.4500
890     7.7500
Name: fare, Length: 491, dtype: float64)

In [77]:
for i,j in dd:
  print(i)
  print(j)

1
1      71.2833
3      53.1000
6      51.8625
11     26.5500
23     35.5000
        ...
871    52.5542
872     5.0000
879    83.1583
887    30.0000
889    30.0000
Name: fare, Length: 216, dtype: float64
2
9      30.0708
15     16.0000
17     13.0000
20     26.0000
21     13.0000
        ...
866    13.8583
874    24.0000
880    26.0000
883    10.5000
886    13.0000
Name: fare, Length: 184, dtype: float64
3
0       7.2500
2       7.9250
4       8.0500
5       8.4583
7      21.0750
        ...
882    10.5167
884     7.0500
885    29.1250
888    23.4500
890     7.7500
Name: fare, Length: 491, dtype: float64

In [79]:
## 데이터프레임 구조 문법의 확장 -> 데이터프레임 -> 데이터프레임 문법 적용된다.

tt.groupby('pclass')['fare'].describe()

        count       mean        std  min       25%      50%   75%       max
pclass
1       216.0  84.154687  78.380373  0.0  30.92395  60.2875  93.5  512.3292
2       184.0  20.662183  13.417399  0.0  13.00000  14.2500  26.0   73.5000
3       491.0  13.675550  11.778142  0.0   7.75000   8.0500  15.5   69.5500

In [80]:
tt.groupby('pclass')[['fare','age']].describe()

         fare                                                                \
        count       mean        std  min       25%      50%   75%       max
pclass
1       216.0  84.154687  78.380373  0.0  30.92395  60.2875  93.5  512.3292
2       184.0  20.662183  13.417399  0.0  13.00000  14.2500  26.0   73.5000
3       491.0  13.675550  11.778142  0.0   7.75000   8.0500  15.5   69.5500

          age
        count       mean        std   min   25%   50%   75%   max
pclass
1       186.0  38.233441  14.802856  0.92  27.0  37.0  49.0  80.0
2       173.0  29.877630  14.001077  0.67  23.0  29.0  36.0  70.0
3       355.0  25.140620  12.495398  0.42  18.0  24.0  32.0  74.0

In [ ]:
## 각 그룹에서 클래스에 따른 성별의 생존율

tt.groupby(['pclass','sex'])['survived'].count()  # 총 인원

pclass  sex
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
Name: survived, dtype: int64

In [ ]:
tt.groupby(['pclass','sex'])['survived'].sum()  # 생존자 수 ('survived == 1'의 합들)

pclass  sex
1       female    91
        male      45
2       female    70
        male      17
3       female    72
        male      47
Name: survived, dtype: int64